### ISSUE TITLE
[Feature Request]Move cig packs, match packs, lolipop and lighter from magazine list to item list.

### ISSUE THREAD

**Issue by GoldJohnKing** [rebelvg/immersion_cigs#10]
Cig packs, match packs, lolipop and lighter should be considered as items instead of magazine, and it's really hard to find in magazine list for the mass amounts of items in magazine list.

So, would you please move cig packs, match packs, lolipop and lighter from magazine list to item list?

**Comment by rebelvg** [comment]
@GoldJohnKing they were specifically moved to magazines so it was possible to track how many cigarettes were taken from a cigpack. It's not possible to do that if they are configured as in-game items.

**Comment by GoldJohnKing** [comment]
Ah, I get your point.
So what about adding a prefix to all these items?

**Comment by rebelvg** [comment]
That could be a solution. I'm also thinking about maybe adding them back as items but convert them to mags at the start of the game. Or maybe converting them to mags on some "inventory changed" event if there's any.

**Comment by OverlordZorn** [comment]
> That could be a solution. I'm also thinking about maybe adding them back as items but convert them to mags at the start of the game. Or maybe converting them to mags on some "inventory changed" event if there's any.

could convert to Magazine once used once
