### ISSUE TITLE
Project inactive?

### ISSUE THREAD

**Issue by OverlordZorn** [rebelvg/immersion_cigs#18]
Hi - I added a couple of Pullrequests for some QoL fixes some 3~4 Months ago and have not recieved any indications of them being acknowledged in any way, therefore i would like to ask for permission to re-release the mod with these changes and to maintain it within my capabilities.

**Comment by rebelvg** [comment]
I am from Ukraine and open-source is not a priority for me at the moment.
I will get back to supporting my mods sometime in the future.

**Comment by OverlordZorn** [comment]
Thanks for awnsering. I can see and understand your current circumstances. 

May i ask for permission to include a modified version of this mod in our units auxilliary mod? Of course only temporary until you have the time to support your mods again yourself.

Слава Україні!

**Comment by rebelvg** [comment]
Sure, you can include the mod.
Thanks for your support of Ukraine.

**Comment by OverlordZorn** [comment]
Hi @rebelvg - I choose to uploaded the changes as a seperate mod, which basically just overwrites 1 function and adds a 2. Action while keeping dependency to the original mod.

Here is the link to the workshop item.
https://steamcommunity.com/sharedfiles/filedetails/?id=3146026772

And here is the link to the github repo.
https://github.com/PulsarNeutronStar/Immersion-Cigs-Hotfix

I made sure to mention the original authors and linked to your workshop item and github.
If you wish to adapt sth, please let me know :)
