### ISSUE TITLE
BIS_fnc_MP is obsolete

### ISSUE THREAD

**Issue by Luigium** [rebelvg/immersion_cigs#2]
Hello,

First, sorry for my bad english, i'm french. :no_mouth:
**BIS_fnc_MP** is now obsolete (https://community.bistudio.com/wiki/BIS_fnc_MP), do you have an idea for the update BIS_fnc_MP in your code ?

I thought about **remoteExec** (https://community.bistudio.com/wiki/remoteExec _or_ https://community.bistudio.com/wiki/remoteExecCall) but it requires a whitelist for multiplayer servers :confused:

Thank you in advance
Luigi

**Comment by rebelvg** [comment]
I'm not sure there's a reason to change it at all. I mean, they're not gonna remove it, it will stay there for the backwards compatibility and serves the purpose completely. As I understand BIS_fnc_MP is now automaticly translated into remoteExec, so it will still need whitelisting anyway.

**Comment by rebelvg** [comment]
https://github.com/rebelvg/immersion_cigs/commit/214d21efdd5cf493274d732847398fc60465d991
