### ISSUE TITLE
Cigarette at night

### ISSUE THREAD

**Issue by KRDucky** [rebelvg/immersion_cigs#6]
The Cigarette doesnt show at night as lit. It doesnt glow.

**Comment by rebelvg** [comment]
Works for me.
http://imgur.com/a/Pjtip

**Comment by KRDucky** [comment]
well for some reason, it doesnt glow and I dont see the puff of smoke

**Comment by rebelvg** [comment]
Check the readme for the mod. You have to start the cig to see the smoke.

**Comment by KRDucky** [comment]
but how do I do that in real time in game on a MP server? Shouldnt it
happen automatically when you light the cigarette?

**Comment by rebelvg** [comment]
https://www.youtube.com/watch?v=MPvKR3VtrEI
This video pretty much shows how it should work.

**Comment by KRDucky** [comment]
But how do you implement that line of code in a mission file?

**Comment by rebelvg** [comment]
I'm not sure what you mean.
You don't need to change anything, it should work as is.

**Comment by KRDucky** [comment]
It doesnt. You said I had to execute the line of code at the bottom of the
readme to make the effects work (puff of smoke etc). Currently all that
happens is the cig is in the mouth and slowly gets smaller.

**Comment by rebelvg** [comment]
I didn't say you had to execute a line of code. I was talking about ingame section of the readme.
What other mods are you running? Have you tried using vanilla only? It works, I checked when you first reported.

**Comment by mrpacman101** [comment]
@KRDucky 
I don't have any issues with his mod and i am even using a lot of other mods combined even on Dedicated Sessions with other players. 
You should probably try to describe your problem better maybe list your mods which you used, if it was singleplayer, multiplayer or dedicated and attach your .rpt file.

**Comment by KRDucky** [comment]
MP. CUP and ACE3 and NIArms. A3Wasteland mission. You can light a cigarette
but there is no smoke and no lit indication. (

**Comment by mrpacman101** [comment]
Did you used all CUP Mods (vehicles, factions, weapons), or just CUP Maps?

**Comment by rebelvg** [comment]
We use all cup and never had any compatibility issues. It's probably that wasteland mission.
