### ISSUE TITLE
Disable autoforce cigaretes + lolipops into loadout

### ISSUE THREAD

**Issue by m1kesk** [rebelvg/immersion_cigs#7]
When we have this mod enabled it forces cigaretes and lolipops into gear of units. 
**This is UNWANTED in most scenarios.**

_Please DO NOT FORCE item into loadouts._ 

Do not get me wrong, this is great immersion, but I as mission maker want to choose when do I want to have those items in loadouts.

**Comment by rebelvg** [comment]
It does this only in singleplayer.

**Comment by m1kesk** [comment]
Why is this there? I don't see any point of this. 
Mission maker have to manually remove those from each unit with script.

Just note:
We had several issues with this when MM created mission, then we deleted this addon from modpack and he did not have any those items in gears, but he needed to replace all units to "run" mission again because of those items forced into gears.

**Comment by m1kesk** [comment]
Same goes for lolipops.

I can delete those from PBO, but I don't want to broke any of your license, tho I created this ticket.

**Comment by rebelvg** [comment]
For people that play singleplayer and don't want to unpack missions to add cigs. As a mission maker you obviously have more control and can clear cigs from loadouts. I can add a CBA option, or add cigs only for true singleplayer, not editor.

**Comment by rebelvg** [comment]
And yes, you can remove these lines from PBO and use them like that in your community. License is purely for public releasing as part of other mods.

**Comment by mrpacman101** [comment]
i don't have any issues in Multiplayer/Dedicated in our community also it wasn't adding anything on multiplayer missions. I get the point but singleplayer missions is just one guy to edit in the editor. I don't understand the issue. Maybe you are building your missions wrong?

**Comment by rebelvg** [comment]
It appears there's no way to detect if the game is running in the editor mode.
```is3DEN``` only works in the editor itself.
So I've added a variable the mission makers can set for the mod not to add any items automatically.
```immersion_cigs_giveItemsInSP = false;```

**Comment by rebelvg** [comment]
https://github.com/rebelvg/immersion_cigs/commit/4ace3406eea0f531ca580142e36c093d6c5ee3b7
